; Basic HDMI tty routines for the nano-Z80

tty_write:
        push af
tty_write_wait:
        call tty_delay
        ;in a, (TTY_BUSY_AVAIL)
        ;or a
        ;jr nz, tty_write_wait
       
        ; Get character from stack
        pop af

        ; Write byte to tty
        out (TTY_WRITE_AVAIL),a
        
        ret

tty_delay:
        ld a,0
tty_delay_loop:
        inc a
        cp a, 20
        jr nz, tty_delay_loop
        ret
